=== raml-apis/Blogger/schemas/user-schema.json
{
  "required" : true ,
  "$schema" : "http://json-schema.org/draft-03/schema" ,
  "type" : "object" ,
  "properties" : {
    "kind" : {
      "type" : "string" ,
      "required" : false
    } ,
    "id" : {
      "type" : "string" ,
      "required" : false
    } ,
    "created" : {
      "type" : "string" ,
      "required" : false
    } ,
    "url" : {
      "type" : "string" ,
      "required" : false
    } ,
    "selfLink" : {
      "type" : "string" ,
      "required" : false
    } ,
    "blogs" : {
      "type" : "object" ,
      "required" : false ,
      "properties" : {
        "selfLink" : {
          "type" : "string" ,
          "required" : false
        }
      }
    } ,
    "displayName" : {
      "type" : "string" ,
      "required" : false
    } ,
    "about" : {
      "type" : "string" ,
      "required" : false
    } ,
    "locale" : {
      "type" : "object" ,
      "required" : false ,
      "properties" : {
        "language" : {
          "type" : "string" ,
          "required" : false
        } ,
        "country" : {
          "type" : "string" ,
          "required" : false
        } ,
        "variant" : {
          "type" : "string" ,
          "required" : false
        }
      }
    }
  }
}

=== raml-apis/Blogger/examples/user-example.json
{
  "kind" : "blogger#user" ,
  "id" : "string" ,
  "created" : "datetime" ,
  "url" : "string" ,
  "selfLink" : "string" ,
  "blogs" : {
    "selfLink" : "string"
  } ,
  "displayName" : "string" ,
  "about" : "string" ,
  "locale" : {
    "language" : "string" ,
    "country" : "string" ,
    "variant" : "string"
  }
}
